mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'deadline/', include('task.urls'))
]

task/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = 'task'
urlpatterns = [
    url(r'^home/$', views.calendar, name='calendar'),
    url(r'^calendar/([0-9]{4})/([0-9]+)/([0-9]+)/$', views.calendar, name='calendar'),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    url(r'^archive/$', views.ArchiveView.as_view(), name='archive'),
    url(r'^upcoming/$', views.UpcomingView.as_view(), name='upcoming'),
    url(r'^add_task/$', views.AddNewTask.as_view(), name='add_task'),
    url(r'^add_task/([0-9]{4})/([0-9]+)/([0-9]+)/$', views.AddDateTask.as_view(), name='add_task_date'),
    url(r'^(?P<pk>[0-9]+)/$', views.TaskDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.EditTask.as_view(), name='edit'),
    url(r'^(?P<pk>[0-9]+)/postpone/$', views.task_procrastinate, name='task_procrastinate'),
    url(r'^(?P<pk>[0-9]+)/invert/$', views.task_invert, name='task_invert'),
    url(r'^(?P<pk>[0-9]+)/remove/$', views.task_remove, name='task_remove'),
]

task/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.core.urlresolvers import reverse


class Task(models.Model):
    
    TASK_IMPORTANCE = (
    ('1', 'low'),
    ('2', 'normal'),
    ('3', 'high'),
    )
    
    short_command = models.CharField(max_length=30, verbose_name="task")
    date = models.DateField(default=datetime.date.today)
    time = models.TimeField(blank=True, null=True)
    deadline = models.DateField(blank=True, null=True)
    importance = models.CharField(
        max_length=1,
        choices=TASK_IMPORTANCE,
        default='2',)
    description = models.TextField(
        verbose_name="Description",
        blank=True, null=True)
    done = models.BooleanField(default=False)
    
    def __str__(self):
        return self.short_command

    def get_absolute_url(self):
        return reverse('task:detail', kwargs={'pk': self.id}) 

    def invert(self):
        if self.done == True:
            self.done = False
        else:
            self.done = True
        self.save()
        
    def procrastinate(self):
        self.date += datetime.timedelta(days=1)
        self.save()

task/forms.py
from django import forms
from .models import Task
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from functools import partial
DateInput = partial(forms.DateInput, {'class': 'datepicker'})
TimeInput = partial(forms.TimeInput, {'class': 'timepicker'})

class AddTask(forms.ModelForm):
    date = forms.DateField(widget=DateInput())
    deadline = forms.DateField(widget=DateInput(), required=False)
    time = forms.TimeField(widget=TimeInput(), required=False)
    
    class Meta:
        model = Task
        help_texts = {
            'importance': 'Choose how important is that task to you',
            'description': 'Fields time, deadline and description are optional.',
        }
        fields = ('short_command', 'importance', 'date', 'time', 'deadline', 'description')

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('login', 'Submit', css_class='btn btn-default'))

class AddTaskDate(forms.ModelForm):
    deadline = forms.DateField(widget=DateInput(), required=False)
    time = forms.TimeField(widget=TimeInput(), required=False)
    
    class Meta:
        model = Task
        help_texts = {
            'importance': 'Choose how important is that task to you.',
            'description': 'Fields time, deadline and description are optional.'
        }
        fields = ('short_command', 'importance', 'time', 'deadline', 'description',)

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('login', 'Submit', css_class='btn btn-default'))
    

task/views.py
from django.shortcuts import render
from django.utils import timezone
from django.views import generic
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404 , redirect, render_to_response
from django.utils.safestring import mark_safe

import datetime
import calendar

from .models import Task
from .forms import AddTask, AddTaskDate
from .event_calendar import TaskCalendar

class SearchView(generic.ListView):
    
    template_name = 'task/search.html'

    def get_queryset(self):
        return Task.objects.all().order_by('-date')

    def get_context_data(self, *args, **kwargs):
        context = super(SearchView, self).get_context_data(*args, **kwargs)

        errors = []
        if 'q' in self.request.GET:
            q = self.request.GET['q']
            if not q:
                errors.append('Please enter a search term.')
                context['errors'] = errors
            elif len(q) > 30:
                errors.append('Please enter at most 30 characters.')
                context['errors'] = errors
            else:
                if 'f' in self.request.GET:
                    f = self.request.GET['f']
                    if f == "display_upcoming":
                        tasks = Task.objects.filter(short_command__icontains=q).extra(where=["date > %s"], params=[timezone.now()])
                else:
                    tasks = Task.objects.filter(short_command__icontains=q)
                context['tasks'] = tasks
                context['query'] = q
        else:
            context['tasks'] = []
        return context
    
class ArchiveView(generic.ListView):
    
    template_name = 'task/task_list.html'
    context_object_name = 'tasks'

    def get_queryset(self):
        return Task.objects.all().filter(date__lt=timezone.now()).order_by('-date')[:20]

    def get_context_data(self, *args, **kwargs):
        context = super(ArchiveView, self).get_context_data(*args, **kwargs)
        context['deadlines'] = Task.objects.all().filter(deadline__lt=timezone.now()).order_by('-deadline')[:20]
        context['past'] = True
        return context

class UpcomingView(generic.ListView):
    
    template_name = 'task/task_list.html'
    context_object_name = 'tasks'

    def get_queryset(self):
        return Task.objects.all().filter(date__gt=timezone.now()).order_by('date')[:20]

    def get_context_data(self, *args, **kwargs):
        context = super(UpcomingView, self).get_context_data(*args, **kwargs)
        context['deadlines'] = Task.objects.all().filter(deadline__gt=timezone.now()).order_by('deadline')[:20]
        return context
    
class TaskDetailView(generic.DetailView):

    template_name = 'task/task_detail.html'
    model = Task
    
    
class AddNewTask(generic.FormView):
    
    template_name = 'task/add_task.html'
    form_class = AddTask
    success_url =  reverse_lazy('task:calendar')
    
    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect(self.get_success_url())
    
class AddDateTask(generic.FormView):
    
    template_name = 'task/add_task.html'
    form_class = AddTaskDate

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        add_form = AddTaskDate()
        date = datetime.date(year=int(self.args[0]), month=int(self.args[1]), day=int(self.args[2]))
        context.update({'add_form': add_form, 'date': date})
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):

        add_form = AddTaskDate(request.POST)
        
        if add_form.is_valid():
            form = add_form.save(commit=False)
            form.date = datetime.date(year=int(self.args[0]), month=int(self.args[1]), day=int(self.args[2]))
            form.save()
            return HttpResponseRedirect(reverse('task:calendar', args=(self.args)))

        context = self.get_context_data(**kwargs)
        context.update({'add_form': add_form, 'date': self.date})
        return self.render_to_response(context)

class EditTask(generic.UpdateView):
    
    template_name = 'task/add_task.html'
    form_class = AddTask
    model = Task

    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect(self.get_success_url())
    
def task_procrastinate(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.procrastinate()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def task_invert(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.invert()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def task_remove(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def calendar(request, year=timezone.now().year, month=timezone.now().month, day=timezone.now().day):
    """
    http://uggedal.com/journal/creating-a-flexible-monthly-calendar-in-django/
    """
    # important: list of deadlines for particular day
    deadlines = Task.objects.order_by('deadline').filter(
    deadline__year=year, deadline__month=month, deadline__day=day)

    # important: list of tasks for particular day
    day_tasks = Task.objects.order_by('date').filter(
    date__year=year, date__month=month, date__day=day)

    # important to create HTMLCalendar
    my_deadlines = Task.objects.order_by('deadline').filter(
    deadline__year=year, deadline__month=month)

    # important to create HTMLCalendar
    my_tasks = Task.objects.order_by('date').filter(
    date__year=year, date__month=month)

    # important to determine the name of particular day
    my_year = int(year)
    my_month = int(month)
    my_day = int(day)

    date = datetime.date(year=my_year,day=my_day, month=my_month)
    
    if my_year == timezone.now().year and my_month == timezone.now().month:
        if my_day == timezone.now().day:
            name = 'today'
        elif my_day == (timezone.now() + datetime.timedelta(days=1)).day:
            name = 'tomorrow'
        elif my_day == (timezone.now() + datetime.timedelta(days=2)).day:
            name = 'day after tomorrow'
        elif my_day == (timezone.now() - datetime.timedelta(days=1)).day:
            name = 'yesterday'
        else:
            name = ''
    else:
        name = ''
        
    # important to handle the change of months and years        
    my_previous_year = my_year
    my_previous_month = my_month - 1
    if my_previous_month == 0:
            my_previous_year = my_year - 1
            my_previous_month = 12
    my_next_year = my_year
    my_next_month = my_month + 1
    if my_next_month == 13:
            my_next_year = my_year + 1
            my_next_month = 1
    my_year_after_this = my_year + 1
    my_year_before_this = my_year - 1

    # calendar
    cal = TaskCalendar(my_tasks, my_deadlines).formatmonth(int(year), int(month))
    return render_to_response('task/calendar.html', {'calendar': mark_safe(cal),
                                                     'my_tasks': day_tasks,
                                                     'deadlines': deadlines,
                                                     'day': my_day,
                                                     'month': my_month,
                                                     'year': my_year,
                                                     'date': date,
                                                     'name': name, 
                                                     'previous_month': my_previous_month,
                                                     'previous_year': my_previous_year,
                                                     'next_month': my_next_month,
                                                     'next_year': my_next_year,
                                                     'year_before_this': my_year_before_this,
                                                     'year_after_this': my_year_after_this,})
        

task/templates/task/add_task.html
{% extends 'task/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Add task
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        {% if date %}
            <h3>Add a new task with date: {{date|date:"j F Y"}}</h3>
        {% else %}
            <h3>Add a new task </h3>
        {% endif %}
        <hr>
    </div>

    <div class="row">
        <div class="col-md-5">
            {% crispy form %}
        </div>
    </div>
    <hr>
</div>
{% endblock%}

task/templates/task/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title%} Deadline {% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{%static 'task/css/style.css'%}">
    <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'task:calendar'%}"><img src="{% static 'task/images/home.svg' %}" alt='home' class="home" />
            </a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'task:add_task'%}">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; Add task
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'task:upcoming' %}">
                        <span class="glyphicon glyphicon-pushpin" aria-hidden="true"></span>&nbsp; Upcoming tasks
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'task:archive' %}">
                        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp; Archive
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'task:search'%}">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>&nbsp; Search tasks
                    </a>
                </li>
                <li class="">
                    <a href="">
                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>&nbsp; About project</a>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container main">
    {% block body%}
    {% endblock %}
</div>


<footer>
    <div class="container">
        <div class="row">
            <div class="col-sm-2">
                <h6>Copyright &copy; 2016 deadline</h6>
            </div>
        </div>

    </div>
</footer>

<script >
$(document).ready(function() {
    $('.datepicker').datepicker();
});
$(document).ready(function(){
    $('input.timepicker').timepicker({
        timeFormat: 'HH:mm',
        startTime: '12:00'
    });
});
</script>

<script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
</body>
</html>

task/templates/task/calendar.html
{% extends 'task/base.html' %}
{% load staticfiles %}

{% block title %}
    Calendar
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <center><img src="{% static 'task/images/logo.png' %}" alt='logo' class="logo" /></center>
    </div>
    <hr>
    <div class="row">

        <div class="col-md-1 left_panel">
            <a href="{% url 'task:calendar' year previous_month day%}">
                <h2><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span></h2>Last month
            </a>
            <a href="{% url 'task:calendar' year_before_this month day %}">
                <h2><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span></h2>Last year
            </a>
        </div>

        <div class="col-md-4 calendar bottom_panel">
            {{ calendar|safe }}
            <ul class="list-inline">
                <li>
                    <a href="{% url 'task:calendar' %}">
                        <h1><span class="glyphicon glyphicon-home" aria-hidden="true"></span></h1>Today
                    </a>
                </li>
                <li>
                    <a href="{% url 'task:add_task_date' year month day%}">
                        <h1><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></h1>Add task
                    </a>
                </li>
                <li>
                    <a href="{% url 'task:search' %}">
                        <h1><span class="glyphicon glyphicon-search" aria-hidden="true"></span></h1>Search
                    </a>
                </li>
            </ul>
        </div>

        <div class="col-md-1 right_panel">
            <a href="{% url 'task:calendar' year next_month day%}">
                <h2><span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></h2>Next month
            </a>
            <a href="{% url 'task:calendar' year_after_this month day%}">
                <h2><span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></h2>Next year
            </a>
        </div>

        <div class="col-md-6 calendar_page">
            <div>
                <h1 class="main_day_name">
                    {% if name %}
                        {{name}}
                    {% else %}
                        {{date|date:"j F Y"}}
                    {% endif %}
                </h1>
            </div>
            <div class="table-responsive">
                {% if deadlines %}
                    <h4>
                        <strong>{{ deadlines|length }}</strong> deadline{{ deadlines|pluralize}}
                    </h4>
                    <table class="table table-hover different-table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Importance</th>
                                <th>Completion</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for deadline in deadlines%}
                            <tr>
                                <td>
                                    <a href="{% url 'task:detail' deadline.id%}">{{deadline.short_command}}</a>
                                </td>
                                {% if deadline.importance == '1' %}
                                    <td>
                                        <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                                    </td>
                                {% elif deadline.importance == '2' %}
                                    <td>
                                        <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                                        <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                                    </td>
                                {% else %}
                                    <td>
                                        <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                                        <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                                        <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                                    </td>
                                {% endif %}
                                {% if deadline.done %}
                                    <td>
                                        <a href="{% url 'task:task_invert' pk=deadline.id %}"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></a>
                                    </td>
                                {% else %}
                                    <td>
                                        <a href="{% url 'task:task_invert' pk=deadline.id %}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                                    </td>
                                {% endif %}
                                    <td>
                                        <a href="{% url 'task:task_remove' pk=deadline.id %}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                                    </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% endif %}
            </div>
            {% if my_tasks %}
                <h4>
                    <strong>{{ my_tasks|length }}</strong> task{{my_tasks|pluralize}}
                </h4>
                <table class="table table-hover different-table">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Importance</th>
                            <th>Completion</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for task in my_tasks%}
                        <tr>
                            <td>
                                <a href="{% url 'task:detail' task.id%}">{{task.short_command}}</a>
                            </td>
                            {% if task.importance == '1' %}
                                <td>
                                    <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                                </td>
                            {% elif task.importance == '2' %}
                                <td>
                                    <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                                    <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                                </td>
                            {% else %}
                                <td>
                                    <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                                    <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                                    <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                                </td>
                            {% endif %}
                            {% if task.done %}
                                <td>
                                    <a href="{% url 'task:task_invert' pk=task.id %}"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></a>
                                </td>
                            {% else %}
                                <td>
                                    <a href="{% url 'task:task_invert' pk=task.id %}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                                </td>
                            {% endif %}
                                <td>
                                    <a href="{% url 'task:task_remove' pk=task.id %}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                                </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p> No task planned <3 </p>
            {% endif %}
        </div>

    </div>
    <hr>
</div>
{% endblock%}

task/templates/task/index.html
{% extends 'task/base.html' %}

{% block title %}
Tasks
{% endblock %}

{% block body %}
    <div class="row text-center">
        <h3 class="index-header"> Check out upcoming tasks </h3>
        <a href="{% url 'task:calendar' %}" class="btn btn-primary btn-lg">Today</a>
        <a href="{% url 'task:index' %}" class="btn btn-primary btn-lg">This week</a>
        <a href="{% url 'task:index' %}" class="btn btn-primary btn-lg">This month </a><br><br>
    </div>
    <div class="container">
    <div class="row">
        {% if tasks %}
          <p>Found {{ tasks|length }} task{{ tasks|pluralize}}.</p>
            <ul class="list-inline">
              {% for task in tasks %}
                <div class="col-md-4 ">
                  <li>
                    <!-- <img src="http://placehold.it/100x100"> -->
                    <h3 class="text-uppercase"><a href="{% url 'task:detail' pk=task.id%}">{{task.short_command}}</a></h3>
                    <p>
                    To do: {{task.date}}
                    </p>
                  </li>
                </div>
              {% endfor %}
            </ul>
        {% else %}
          {% if query %}
            <p>No task matched your search criteria.</p>
          {% endif %}
        {% endif %}
    </div>
  </div>
{% endblock%}

task/templates/task/search.html
{% extends 'task/base.html' %}

{% block title %}
    Search
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="form-group">
            <form action="" method='get'>
                <input type="text" name="q" placeholder="Search tasks" class="form-control" value="{{request.GET.q}}" /><br>
                <input type="checkbox" name="f" value="display_upcoming"/> Only upcoming tasks
            </form>
        </div>
        <hr>
    </div>
    <div class="row">
        {% if errors %}
            {% for error in errors %}
                <p>{{error}}</p>
            {% endfor %}
        {% elif tasks %}
            <p>Found {{ tasks|length }} task{{ tasks|pluralize}}.</p>
            <ul class="list-inline">
                {% for task in tasks %}
                    <div class="col-md-4 ">
                        <li>
                            <h3 class="text-uppercase"><a href="{% url 'task:detail' pk=task.id%}">{{task.short_command}}</a></h3>
                            <p>To do: {{task.date|date:"j M Y"}}</p>
                        </li>
                    </div>
                {% endfor %}
            </ul>
        {% else %}
            {% if query %}
                <p>No task matched your search criteria.</p>
            {% endif %}
        {% endif %}
    </div>
    <hr>
</div>
{% endblock%}

task/templates/task/task_detail.html
{% extends 'task/base.html' %}

{% block title %}
    {{ task.short_command }}
{% endblock %}

{% block body %}
<div class="row">
    <div class=" col-md-5">
        <ul class="list-inline small_menu">
            {% if task.done %}
                <li>
                    <a href="{% url 'task:task_invert' pk=task.id %}"><h1><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></h1>Mark as not done </a>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'task:task_invert' pk=task.id %}"><h1><span class="glyphicon glyphicon-ok" aria-hidden="true"></h1></span> Mark as done </a>
                </li>
                <li>
                    <a href="{% url 'task:task_procrastinate' pk=task.id %}"><h1><span class="glyphicon glyphicon-forward" aria-hidden="true"></span></h1>Procrastinate</a>
                </li>
            {% endif%}
                <li>
                    <a href="{% url 'task:edit' pk=task.id %}"><h1><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></h1>Edit task </a>
                </li>

                <li>
                    <a href="{% url 'task:calendar' task.date.year task.date.month task.date.day %}"><h1><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span></h1>Calendar </a>
                </li>

                <li>
                    <a href="{% url 'task:task_remove' pk=task.id %}"><h1><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></h1>Delete </a>
                </li>
        </ul>

        <h2>{{ task.short_command }}
            {% if task.importance == '1' %}
                <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
            {% elif task.importance == '2' %}
                <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
            {% else %}
                <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
            {% endif %}
        </h2>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th>
                        Status
                    </th>
                    <th>
                        {% if task.done %}
                            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                        {% else %}
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        {% endif %}
                    </th>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <td>
                        Date
                    </td>
                    <td>
                        {{task.date|date:"j M Y"}}
                    </td>
                </tr>
                {% if task.time %}
                    <tr>
                        <td>
                            Time
                        </td>
                        <td>
                            {{task.time}}
                        </td>
                    </tr>
                {% endif %}
                <tr>
                    <td>
                        Description
                    </td>
                    <td>
                        {{task.description}}
                    </td>
                </tr>
                {% if task.deadline %}
                    <tr>
                        <td>
                            Deadline
                        </td>
                        <td>
                            {{task.deadline|date:"j M Y"}}
                        </td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
    </div>

    <div class=" col-md-7">
    </div>
</div>
{% endblock%}